networks:
  dev:

services:
   db:
     image: postgres:15
     container_name: db_szfo_hack
     env_file:
       - ./backend/config.env
     networks:
       - dev
    
   app:
     build:
      context: ./backend
     env_file:
      - ./backend/config.env 
     container_name: fastapi_back_2
     ports:
      - 9999:8000
     depends_on:
      - db
     
     networks:
      - dev

   nginx-react:
    container_name: frontend_2
    build:
      context: ./frontend/szfo_web
    ports:
      - 3000:3000
    networks:
      - dev

   nginx:
      image: nginx:stable-alpine
      ports:
       - "3333:3333"
       - "443:443"
      volumes:
       - './nginx.conf:/etc/nginx/nginx.conf'
       - '/etc/letsencrypt:/etc/letsencrypt'
      depends_on:
       - app 
       - nginx-react 
      networks:
       - dev
